### ISSUE TITLE
Frontend roadmap

### ISSUE THREAD

**Issue by matthewkirby** [matthewkirby/RSLLeaderboard#16]
Since I just finished the refactor from the "it works, ship it" version of the frontend. I wanted to just write down my next steps
- [x] Site Navigation and conversion from SPA with React Router
- [x] Rated async page
- [x] Seasonal races page

The race pages (rated async/races in a season) will just be a single component that makes an api request for a list of races and then builds a Table component for each race. The different pages (rated async, seasonal races, off-season, user) simply differ in the initial backend request.

Other plans, havent decided if I want them in the first official release or not yet
- [ ] View all races by a single racer (although this will be trivially easy)

**Comment by matthewkirby** [comment]
I am leaving single player's races as a future enhancement. Issue #23
